services:
  app:
    environment:
      - DB_NAME=${DB_NAME}
        DB_USER=${DB_USER}
        DB_PASS=${DB_PASS}
    build:
      context: .
      dockerfile: ./Dockerfile.multistage
    ports:
      - "8080:8080"

  db:
    environment:
      - POSTGRES_DB=${DB_NAME}
        POSTGRES_USER=${DB_USER}
        POSTGRES_PASSWORD=${DB_PASS}
    build:
      context: .
      dockerfile: ./Dockerfile.pg

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8083