services:
  app:
    environment:
      - DB_NAME=${DB_NAME}
        DB_USER=${DB_USER}
        DB_PASS=${DB_PASS}
    build:
      context: ./../../../
      dockerfile: ./src/main/docker/Dockerfile.multistage
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - pedeai

  db:
    environment:
      - POSTGRES_DB=${DB_NAME}
        POSTGRES_USER=${DB_USER}
        POSTGRES_PASSWORD=${DB_PASS}
    build:
      context: .
      dockerfile: ./Dockerfile.pg
    networks:
      - pedeai

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080

networks:
  pedeai:
    driver: bridge