apiVersion: v1
kind: PersistentVolume
metadata:
  name: pedeai-db-pv
spec:
  capacity:
    storage: 5Gi
  # volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: /data/pedeai-db-pv
  # persistentVolumeReclaimPolicy: Delete
  # storageClassName: local-storage
  # local:
  #   path: /tmp/pedeai-pv
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #           - minikube
